name: Automatic Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: identicon.starknet.id
      SSH_USER: ubuntu
      REPO_PATH: '~/identicon.starknet.id'
    steps:
      - name: Setting up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Remote deployment
        run: |
          ssh -o StrictHostKeyChecking=no -T $SSH_USER@$SSH_HOST << EOF
            export REPO_PATH=$REPO_PATH
            export GIT_SSH_COMMAND='ssh -i ~/.ssh/github_read -o IdentitiesOnly=yes'
            
            # Configure AWS CLI
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION

            cd api.starknet.id/
            sudo docker compose down identicon_server
            cd ../

            if [ -d "\$REPO_PATH/.git" ]; then
              echo "Repository exists, pulling changes..."
              cd \$REPO_PATH
              git reset --hard HEAD
              git pull
            else
              echo "Repository doesn't exist, cloning..."
              mkdir -p \$REPO_PATH
              git clone git@github.com:starknet-id/identicon.starknet.id.git \$REPO_PATH
              cd \$REPO_PATH
            fi

            # Use AWS CLI to copy configuration files from S3
            sudo chown -R \$SSH_USER:\$SSH_USER \$REPO_PATH
            sudo chmod -R 755 \$REPO_PATH
            aws s3 cp s3://$AWS_PATH/ \$REPO_PATH --recursive

            cd ../api.starknet.id/
            sudo docker compose up --build -d identicon_server

          EOF
